### ISSUE TITLE
Add "Remaining balance" to Confirm Transaction window

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zec-qt-wallet#71]
When a user presses the Send button, a Confirm Transaction window pops up. I would like to see the remaining balance in the sending address after the transaction is sent. For example if I start with 1 ZEC, and send 0.5 with a 0.0001 fee then it should show a remaining balance of 0.4999 in this window.

**Comment by adityapk00** [comment]
I'm in two minds about this. 

On one hand, I want the confirm window to be very very simple, showing exactly the information that will be passed to zcashd. This is a critical window, since it confirms the exact data that will be sent to zcashd, and I want to minimize the surface to keep bugs away. Showing an additional field that is not being sent might cause cognitive overhead (eg., confuse the remaining balance with amount sent). 

Maybe we should show this field elsewhere? Like maybe on the send tab, at the bottom or somewhere?

What do you think?

**Comment by the-metalworker** [comment]
I can understand the desire to keep the confirmation window simple. Putting the remaining balance on the send screen would be a fair compromise to me.

**Comment by adityapk00** [comment]
Maybe we can have a "Change from Tx" row, which shows how much balance will remain. Although it might not be technically accurate, since all UTXOs might not be included by zcashd in the Tx, and the "change" from the Tx might be lower than the total remaining balance.

**Comment by the-metalworker** [comment]
> Although it might not be technically accurate, since all UTXOs might not be included by zcashd in the Tx, and the "change" from the Tx might be lower than the total remaining balance.

That is my thought as well, what I'm looking for is the total remaining balance not just the change amount (which as you point out can be different than the remaining balance).

I can also accept if you aren't able to accommodate this feature request. I appreciate your consideration and responsiveness to these issues I opened!

**Comment by adityapk00** [comment]
In v0.5.5
