### ISSUE TITLE
Add support for connecting over Tor

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zec-qt-wallet#74]
The Bitcoin Core wallet GUI has a setting where you can route node traffic over Tor. I would like to see a feature like this in zec-qt.

**Comment by rex4539** [comment]
By the way, in order to have true onion routing support, you need to connect to Zcash nodes behind onion addresses.

Those nodes need to be entered in `zcash.conf`.

I have gathered a number of those addresses but they are all controlled by a single user, which is currently not very nice for decentralization.

```
addnode=zcmaintvsivr7pcn.onion
addnode=zcashiqykswlzpsu.onion
addnode=zcashqhrmju6zfhn.onion
addnode=zcashgmvxwrmjsut.onion
addnode=zcashz3uma65ix7b.onion
addnode=zcashiyf4kxluf3x.onion
addnode=zcashwfe4x3jkz2b.onion
addnode=zcashvkeki52iqpc.onion
addnode=zcasha3cmfrpy7b7.onion
addnode=zcashz7ed3nvbdxm.onion
addnode=zcash5adwfpxfuvf.onion
addnode=zcashixg5ol2ndo4.onion
addnode=zcashuzwa365oh3n.onion
addnode=zcashskbeoiwtym3.onion
addnode=zcashuyvk5e7qfzy.onion
addnode=fhsxfrwpyrtoxeal.onion
addnode=zcash2iihed2wdux.onion
addnode=w3dxku36wbp3lowx.onion
addnode=zcashuhmzycmlwld.onion
```

Also, `zcashd` supports Tor by itself so you can enter the following in `zcash.conf` to enable connection strictly via Tor:

```
proxy=127.0.0.1:9050
onlynet=onion
```

**Comment by the-metalworker** [comment]
> By the way, in order to have true onion routing support, you need to connect to Zcash nodes behind onion addresses.

What I hope to achieve with the feature requested in this issue is to hide my usage of Zcash from my ISP and nodes that I connect to on the network. A simple proxy configuration routing traffic through Tor will achieve this. Connecting to hidden services nodes exclusively is an improvement but not necessary to achieve what I want from this feature.

> I have gathered a number of those addresses but they are all controlled by a single user, which is currently not very nice for decentralization.

We need more Zcash hidden services! This is an eclipse attack waiting to happen.

> Also, zcashd supports Tor by itself so you can enter the following in zcash.conf to enable connection strictly via Tor

Thanks for the tip. I would like to see this in the GUI so users don't have to mess with the conf file.

**Comment by adityapk00** [comment]
So I played with this over the weekend, but I'm having trouble with the UX, so maybe you guys can help me think it through?

I was thinking "Connect over Tor" will be an option in the settings. Making it work is difficult in all scenarios:

1. If there's an external zcashd:
a. If zcashd is remote:
There's nothing we can do here, since we can't control the zcashd. So maybe the option is disabled
b. If zcashd is local, but external
We could add the following into zcash.conf, but we'll have to ask the user to restart everything
```
proxy=127.0.0.1:9050
onlynet=onion
```
2. If we're using an embedded zcashd
a. First time running, we're creating a new zcash.conf
This is probably the easiest scenario. We can just add the config to zcash.conf and it will connect over tor
b. zcash.conf already exists, blockchain is probably synced.
Here, we'll add to zcash.conf and restart zcashd. 

Embedded zcashd (Scenario (2)) is easier to handle. With an external zcashd, it is harder, so I'm thinking we might not enable the Tor option for external zcashd. We could maybe include instructions, but no automated actions. 

What do you guys think?

**Comment by rex4539** [comment]
I'm in favor of only supporting the embedded zcashd.

If a user knows how to run zcashd externally, he also knows how to configure zcash.conf

Regarding the implementation, I think that `onlynet=onion` is only used when you want want to force connection just with `.onion` Tor hidden services and avoid leaks to clearnet IP addresses. Since this implementation does not add any hidden services to zcash.conf then this flag is not required.

**Comment by adityapk00** [comment]
In v0.5.5

**Comment by garethtdavies** [comment]
I checked the box, the `proxy=` line was added to zcash.conf, I'm using the embedded zcashd but I don't have Tor running and I don't see an error. Is there a way to check that Tor is actually active? Ideally, it would indicate the status something like the "Ready!" status in the footer of the application.

**Comment by adityapk00** [comment]
Thanks for reporting this. Disturbingly, zcashd seems to be silently falling back to the regular connections if it can’t connect to Tor. Maybe we should add the `onlynet` parameter in zcash.conf as well.

**Comment by garethtdavies** [comment]
Sorry, my mistake when testing this - I assumed it was connecting via a non-Tor connection but actually my connections are 0 with the `proxy` setting enabled and Tor not running which is as expected 👍

**Comment by adityapk00** [comment]
Cool, thanks for confirming. I was trying to repro it, and was getting the same behaviour.

Now I'm wondering if it's the right thing to show 'Connected' if `peers==0`. Maybe we should show like "Limited" or something so that people are not mislead. This can happen in other situations too - if you don't have an internet connection, for example.
