### ISSUE TITLE
Show sync progress

### ISSUE THREAD

**Issue by the-metalworker** [ZcashFoundation/zec-qt-wallet#83]
When trying to send, the wallet says "node still syncing", so it seems to have some awareness when it's not caught up to the chain tip. Could this awareness also be used to show progress during syncing? Right now the wallet just shows the current block height synced. But could it also show what the current chain tip is so I can see I have synced X out of Y blocks?

**Comment by adityapk00** [comment]
The limitation here is that the zcashd RPC doesn't have a lot of info on the syncing, so we only show the sync percentage in the status bar on the bottom right. 

If you're using the embedded zcashd, however, you see all the info on the zcashd tab, including the estimated number of blocks remaining and percentage progress.

There's an issue filed with zcashd to track the issue here: https://github.com/zcash/zcash/issues/3726

**Comment by adityapk00** [comment]
Closing this, since there's already an issue on zcashd
